export const surahsData = [
    { id: 1, name_ar: "الفاتحة", name_phonetic: "Al-Fatiha", name_fr: "L'Ouverture", verses_count: 7 },
    { id: 2, name_ar: "البقرة", name_phonetic: "Al-Baqara", name_fr: "La Vache", verses_count: 286 },
    { id: 3, name_ar: "آل عمران", name_phonetic: "Al-Imran", name_fr: "La Famille d'Imran", verses_count: 200 },
    { id: 4, name_ar: "النساء", name_phonetic: "An-Nisa", name_fr: "Les Femmes", verses_count: 176 },
    { id: 5, name_ar: "المائدة", name_phonetic: "Al-Ma'ida", name_fr: "La Table Servie", verses_count: 120 },
    { id: 6, name_ar: "الأنعام", name_phonetic: "Al-An'am", name_fr: "Les Bestiaux", verses_count: 165 },
    { id: 7, name_ar: "الأعراف", name_phonetic: "Al-A'raf", name_fr: "Les Limbes", verses_count: 206 },
    { id: 8, name_ar: "الأنفال", name_phonetic: "Al-Anfal", name_fr: "Le Butin", verses_count: 75 },
    { id: 9, name_ar: "التوبة", name_phonetic: "At-Tawba", name_fr: "Le Repentir", verses_count: 129 },
    { id: 10, name_ar: "يونس", name_phonetic: "Yunus", name_fr: "Jonas", verses_count: 109 },
    { id: 11, name_ar: "هود", name_phonetic: "Hud", name_fr: "Hud", verses_count: 123 },
    { id: 12, name_ar: "يوسف", name_phonetic: "Yusuf", name_fr: "Joseph", verses_count: 111 },
    { id: 13, name_ar: "الرعد", name_phonetic: "Ar-Ra'd", name_fr: "Le Tonnerre", verses_count: 43 },
    { id: 14, name_ar: "إبراهيم", name_phonetic: "Ibrahim", name_fr: "Abraham", verses_count: 52 },
    { id: 15, name_ar: "الحجر", name_phonetic: "Al-Hijr", name_fr: "Al-Hijr", verses_count: 99 },
    { id: 16, name_ar: "النحل", name_phonetic: "An-Nahl", name_fr: "Les Abeilles", verses_count: 128 },
    { id: 17, name_ar: "الإسراء", name_phonetic: "Al-Isra", name_fr: "Le Voyage Nocturne", verses_count: 111 },
    { id: 18, name_ar: "الكهف", name_phonetic: "Al-Kahf", name_fr: "La Caverne", verses_count: 110 },
    { id: 19, name_ar: "مريم", name_phonetic: "Maryam", name_fr: "Marie", verses_count: 98 },
    { id: 20, name_ar: "طه", name_phonetic: "Ta-Ha", name_fr: "Ta-Ha", verses_count: 135 },
    { id: 21, name_ar: "الأنبياء", name_phonetic: "Al-Anbiya", name_fr: "Les Prophètes", verses_count: 112 },
    { id: 22, name_ar: "الحج", name_phonetic: "Al-Hajj", name_fr: "Le Pèlerinage", verses_count: 78 },
    { id: 23, name_ar: "المؤمنون", name_phonetic: "Al-Mu'minun", name_fr: "Les Croyants", verses_count: 118 },
    { id: 24, name_ar: "النور", name_phonetic: "An-Nur", name_fr: "La Lumière", verses_count: 64 },
    { id: 25, name_ar: "الفرقان", name_phonetic: "Al-Furqan", name_fr: "Le Discernement", verses_count: 77 },
    { id: 26, name_ar: "الشعراء", name_phonetic: "Ash-Shu'ara", name_fr: "Les Poètes", verses_count: 227 },
    { id: 27, name_ar: "النمل", name_phonetic: "An-Naml", name_fr: "Les Fourmis", verses_count: 93 },
    { id: 28, name_ar: "القصص", name_phonetic: "Al-Qasas", name_fr: "Le Récit", verses_count: 88 },
    { id: 29, name_ar: "العنكبوت", name_phonetic: "Al-Ankabut", name_fr: "L'Araignée", verses_count: 69 },
    { id: 30, name_ar: "الروم", name_phonetic: "Ar-Rum", name_fr: "Les Romains", verses_count: 60 },
    { id: 31, name_ar: "لقمان", name_phonetic: "Luqman", name_fr: "Luqman", verses_count: 34 },
    { id: 32, name_ar: "السجدة", name_phonetic: "As-Sajda", name_fr: "La Prosternation", verses_count: 30 },
    { id: 33, name_ar: "الأحزاب", name_phonetic: "Al-Ahzab", name_fr: "Les Coalisés", verses_count: 73 },
    { id: 34, name_ar: "سبأ", name_phonetic: "Saba", name_fr: "Saba", verses_count: 54 },
    { id: 35, name_ar: "فاطر", name_phonetic: "Fatir", name_fr: "Le Créateur", verses_count: 45 },
    { id: 36, name_ar: "يس", name_phonetic: "Ya-Sin", name_fr: "Ya-Sin", verses_count: 83 },
    { id: 37, name_ar: "الصافات", name_phonetic: "As-Saffat", name_fr: "Les Rangés", verses_count: 182 },
    { id: 38, name_ar: "ص", name_phonetic: "Sad", name_fr: "Sad", verses_count: 88 },
    { id: 39, name_ar: "الزمر", name_phonetic: "Az-Zumar", name_fr: "Les Groupes", verses_count: 75 },
    { id: 40, name_ar: "غافر", name_phonetic: "Ghafir", name_fr: "Le Pardonneur", verses_count: 85 },
    { id: 41, name_ar: "فصلت", name_phonetic: "Fussilat", name_fr: "Les Versets détaillés", verses_count: 54 },
    { id: 42, name_ar: "الشورى", name_phonetic: "Ash-Shura", name_fr: "La Consultation", verses_count: 53 },
    { id: 43, name_ar: "الزخرف", name_phonetic: "Az-Zukhruf", name_fr: "L'Ornement", verses_count: 89 },
    { id: 44, name_ar: "الدخان", name_phonetic: "Ad-Dukhan", name_fr: "La Fumée", verses_count: 59 },
    { id: 45, name_ar: "الجاثية", name_phonetic: "Al-Jathiya", name_fr: "L'Agenouillée", verses_count: 37 },
    { id: 46, name_ar: "الأحقاف", name_phonetic: "Al-Ahqaf", name_fr: "Al-Ahqaf", verses_count: 35 },
    { id: 47, name_ar: "محمد", name_phonetic: "Muhammad", name_fr: "Muhammad", verses_count: 38 },
    { id: 48, name_ar: "الفتح", name_phonetic: "Al-Fath", name_fr: "La Victoire", verses_count: 29 },
    { id: 49, name_ar: "الحجرات", name_phonetic: "Al-Hujurat", name_fr: "Les Appartements", verses_count: 18 },
    { id: 50, name_ar: "ق", name_phonetic: "Qaf", name_fr: "Qaf", verses_count: 45 },
    { id: 51, name_ar: "الذاريات", name_phonetic: "Adh-Dhariyat", name_fr: "Qui éparpillent", verses_count: 60 },
    { id: 52, name_ar: "الطور", name_phonetic: "At-Tur", name_fr: "Le Mont", verses_count: 49 },
    { id: 53, name_ar: "النجم", name_phonetic: "An-Najm", name_fr: "L'Étoile", verses_count: 62 },
    { id: 54, name_ar: "القمر", name_phonetic: "Al-Qamar", name_fr: "La Lune", verses_count: 55 },
    { id: 55, name_ar: "الرحمان", name_phonetic: "Ar-Rahman", name_fr: "Le Tout Miséricordieux", verses_count: 78 },
    { id: 56, name_ar: "الواقعة", name_phonetic: "Al-Waqi'a", name_fr: "L'Événement", verses_count: 96 },
    { id: 57, name_ar: "الحديد", name_phonetic: "Al-Hadid", name_fr: "Le Fer", verses_count: 29 },
    { id: 58, name_ar: "المجادلة", name_phonetic: "Al-Mujadila", name_fr: "La Discussion", verses_count: 22 },
    { id: 59, name_ar: "الحشر", name_phonetic: "Al-Hashr", name_fr: "L'Exode", verses_count: 24 },
    { id: 60, name_ar: "الممتحنة", name_phonetic: "Al-Mumtahina", name_fr: "L'Éprouvée", verses_count: 13 },
    { id: 61, name_ar: "الصف", name_phonetic: "As-Saff", name_fr: "Le Rang", verses_count: 14 },
    { id: 62, name_ar: "الجمعة", name_phonetic: "Al-Jumu'a", name_fr: "Le Vendredi", verses_count: 11 },
    { id: 63, name_ar: "المنافقون", name_phonetic: "Al-Munafiqun", name_fr: "Les Hypocrites", verses_count: 11 },
    { id: 64, name_ar: "التغابن", name_phonetic: "At-Taghabun", name_fr: "La Grande Perte", verses_count: 18 },
    { id: 65, name_ar: "الطلاق", name_phonetic: "At-Talaq", name_fr: "Le Divorce", verses_count: 12 },
    { id: 66, name_ar: "التحريم", name_phonetic: "At-Tahrim", name_fr: "L'Interdiction", verses_count: 12 },
    { id: 67, name_ar: "الملك", name_phonetic: "Al-Mulk", name_fr: "La Royauté", verses_count: 30 },
    { id: 68, name_ar: "القلم", name_phonetic: "Al-Qalam", name_fr: "La Plume", verses_count: 52 },
    { id: 69, name_ar: "الحاقة", name_phonetic: "Al-Haqqah", name_fr: "Celle qui montre la vérité", verses_count: 52 },
    { id: 70, name_ar: "المعارج", name_phonetic: "Al-Ma'arij", name_fr: "Les Voies d'ascension", verses_count: 44 },
    { id: 71, name_ar: "نوح", name_phonetic: "Nuh", name_fr: "Noé", verses_count: 28 },
    { id: 72, name_ar: "الجن", name_phonetic: "Al-Jinn", name_fr: "Les Djinns", verses_count: 28 },
    { id: 73, name_ar: "المزمل", name_phonetic: "Al-Muzzammil", name_fr: "L'Enveloppé", verses_count: 20 },
    { id: 74, name_ar: "المدثر", name_phonetic: "Al-Muddaththir", name_fr: "Le Revêtu d'un manteau", verses_count: 56 },
    { id: 75, name_ar: "القيامة", name_phonetic: "Al-Qiyama", name_fr: "La Résurrection", verses_count: 40 },
    { id: 76, name_ar: "الإنسان", name_phonetic: "Al-Insan", name_fr: "L'Homme", verses_count: 31 },
    { id: 77, name_ar: "المرسلات", name_phonetic: "Al-Mursalat", name_fr: "Les Envoyés", verses_count: 50 },
    { id: 78, name_ar: "النبأ", name_phonetic: "An-Naba", name_fr: "La Nouvelle", verses_count: 40 },
    { id: 79, name_ar: "النازعات", name_phonetic: "An-Nazi'at", name_fr: "Les Anges qui arrachent", verses_count: 46 },
    { id: 80, name_ar: "عبس", name_phonetic: "Abasa", name_fr: "Il s'est renfrogné", verses_count: 42 },
    { id: 81, name_ar: "التكوير", name_phonetic: "At-Takwir", name_fr: "L'Obscurcissement", verses_count: 29 },
    { id: 82, name_ar: "الانفطار", name_phonetic: "Al-Infitar", name_fr: "La Rupture", verses_count: 19 },
    { id: 83, name_ar: "المطففين", name_phonetic: "Al-Mutaffifin", name_fr: "Les Fraudeurs", verses_count: 36 },
    { id: 84, name_ar: "الانشقاق", name_phonetic: "Al-Inshiqaq", name_fr: "La Déchirure", verses_count: 25 },
    { id: 85, name_ar: "البروج", name_phonetic: "Al-Buruj", name_fr: "Les Constellations", verses_count: 22 },
    { id: 86, name_ar: "الطارق", name_phonetic: "At-Tariq", name_fr: "L'Astre nocturne", verses_count: 17 },
    { id: 87, name_ar: "الأعلى", name_phonetic: "Al-A'la", name_fr: "Le Très-Haut", verses_count: 19 },
    { id: 88, name_ar: "الغاشية", name_phonetic: "Al-Ghashiyah", name_fr: "L'Enveloppante", verses_count: 26 },
    { id: 89, name_ar: "الفجر", name_phonetic: "Al-Fajr", name_fr: "L'Aube", verses_count: 30 },
    { id: 90, name_ar: "البلد", name_phonetic: "Al-Balad", name_fr: "La Cité", verses_count: 20 },
    { id: 91, name_ar: "الشمس", name_phonetic: "Ash-Shams", name_fr: "Le Soleil", verses_count: 15 },
    { id: 92, name_ar: "الليل", name_phonetic: "Al-Layl", name_fr: "La Nuit", verses_count: 21 },
    { id: 93, name_ar: "الضحى", name_phonetic: "Ad-Duha", name_fr: "Le Jour montant", verses_count: 11 },
    { id: 94, name_ar: "الشرح", name_phonetic: "Ash-Sharh", name_fr: "L'Ouverture", verses_count: 8 },
    { id: 95, name_ar: "التين", name_phonetic: "At-Tin", name_fr: "Le Figuier", verses_count: 8 },
    { id: 96, name_ar: "العلق", name_phonetic: "Al-Alaq", name_fr: "L'Adhérence", verses_count: 19 },
    { id: 97, name_ar: "القدر", name_phonetic: "Al-Qadr", name_fr: "La Destinée", verses_count: 5 },
    { id: 98, name_ar: "البينة", name_phonetic: "Al-Bayyina", name_fr: "La Preuve", verses_count: 8 },
    { id: 99, name_ar: "الزلزلة", name_phonetic: "Az-Zalzala", name_fr: "La Secousse", verses_count: 8 },
    { id: 100, name_ar: "العاديات", name_phonetic: "Al-Adiyat", name_fr: "Les Coursiers", verses_count: 11 },
    { id: 101, name_ar: "القارعة", name_phonetic: "Al-Qari'a", name_fr: "Le Fracas", verses_count: 11 },
    { id: 102, name_ar: "التكاثر", name_phonetic: "At-Takathur", name_fr: "La Course aux richesses", verses_count: 8 },
    { id: 103, name_ar: "العصر", name_phonetic: "Al-Asr", name_fr: "Le Temps", verses_count: 3 },
    { id: 104, name_ar: "الهمزة", name_phonetic: "Al-Humaza", name_fr: "Les Calomniateurs", verses_count: 9 },
    { id: 105, name_ar: "الفيل", name_phonetic: "Al-Fil", name_fr: "L'Éléphant", verses_count: 5 },
    { id: 106, name_ar: "قريش", name_phonetic: "Quraysh", name_fr: "Coraïch", verses_count: 4 },
    { id: 107, name_ar: "الماعون", name_phonetic: "Al-Ma'un", name_fr: "L'Ustensile", verses_count: 7 },
    { id: 108, name_ar: "الكوثر", name_phonetic: "Al-Kawthar", name_fr: "L'Abondance", verses_count: 3 },
    { id: 109, name_ar: "الكافرون", name_phonetic: "Al-Kafirun", name_fr: "Les Infidèles", verses_count: 6 },
    { id: 110, name_ar: "النصر", name_phonetic: "An-Nasr", name_fr: "Le Secours", verses_count: 3 },
    { id: 111, name_ar: "المسد", name_phonetic: "Al-Masad", name_fr: "Les Fibres", verses_count: 5 },
    { id: 112, name_ar: "الإخلاص", name_phonetic: "Al-Ikhlas", name_fr: "Le Monothéisme pur", verses_count: 4 },
    { id: 113, name_ar: "الفلق", name_phonetic: "Al-Falaq", name_fr: "L'Aube naissante", verses_count: 5 },
    { id: 114, name_ar: "الناس", name_phonetic: "An-Nas", name_fr: "Les Hommes", verses_count: 6 }
];
